//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebParser.DAL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterPlugin
    {
        public int QID { get; set; }
        public int PluginID { get; set; }
        public string Synopsis { get; set; }
        public string Description { get; set; }
        public bool Reportable { get; set; }
        public string PluginOutPut { get; set; }
        public bool PluginOutputReportable { get; set; }
        public string RiskFactor { get; set; }
        public string Category1 { get; set; }
        public string Category2 { get; set; }
        public string Category3 { get; set; }
        public string Solution { get; set; }
    }
}
