//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebParser.DAL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScanMaster
    {
        public ScanMaster()
        {
            this.CurrScans = new HashSet<CurrScan>();
        }
    
        public int ScanId { get; set; }
        public int SubScanId { get; set; }
        public string ClientName { get; set; }
        public string ScanName { get; set; }
        public System.DateTime ScanDate { get; set; }
        public int Id { get; set; }
        public string UserId { get; set; }
    
        public virtual ICollection<CurrScan> CurrScans { get; set; }
    }
}
