//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebParser.DAL.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebParserEntities : DbContext
    {
        public WebParserEntities()
            : base("name=WebParserEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ComplianceMaster> ComplianceMasters { get; set; }
        public DbSet<CurrScan> CurrScans { get; set; }
        public DbSet<MasterPlugin> MasterPlugins { get; set; }
        public DbSet<ScanMaster> ScanMasters { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<ScanNumber> ScanNumbers { get; set; }
    }
}
